version: '3'
services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: 'true'
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: remitano_backend_prod
    volumes:
      - postgres-data:/var/lib/postgresql/data

  frontend:
    build: ./remitano-frontend
    ports:
      - "80:80"

volumes:
  postgres-data:
